### PR TITLE
Update haproxy to 1.6, redirect /swagger

### PR DESCRIPTION
**Pull request by ebullient**
Update haproxy to v1.6, 
write intelligible rules about redirecting /swagger to /swagger/

---

This change is [Reviewable](https://reviewable.io/reviews/gameontext/gameon-proxy/5)

### CODE REVIEW

**Comment by benjsmi** [comment]
This looks fine to me.  Curious why you moved to 1.6, but it is the latest stable release, so that's fine.

**Comment by ebullient** [comment]
Reviewed 1 of 4 files at r1.
Review status: 1 of 4 files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/gameontext/gameon-proxy/5)_

**Comment by ebullient** [comment]
Reviewed 3 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/gameontext/gameon-proxy/5)_

**Comment by ebullient** [comment]
Http request directive is cleaner and only in 1.6

---

Erin Schnabel schnabel@us.ibm.com
WebSphere Liberty developer/maven/evangelist and Microservices Architect
845.435.5648 / 8.295.5648
i ♥ liberty

**Pull request merged**
